site_name: Информационный портал LS:MP
site_url: http://127.0.0.1:8000

theme:
  language: ru
  name: material

  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.expand
    - navigation.sections

  font:
    text: Inter
    code: IBM Plex Mono

  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette:
    - scheme: slate
      toggle:
        icon: material/moon-waning-crescent
        name: Тёмная тема
      primary: deep purple
      accent: green

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
      primary: deep purple
      accent: green

extra_javascript:
  - assets/js/redirect.js

nav:
  - ℹ️ Основная информация:
      - Главная: index.md